package com.rsna.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class UserPicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userpic
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userpic
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userpic
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public UserPicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userpic
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPicidIsNull() {
            addCriterion("picid is null");
            return (Criteria) this;
        }

        public Criteria andPicidIsNotNull() {
            addCriterion("picid is not null");
            return (Criteria) this;
        }

        public Criteria andPicidEqualTo(Integer value) {
            addCriterion("picid =", value, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidNotEqualTo(Integer value) {
            addCriterion("picid <>", value, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidGreaterThan(Integer value) {
            addCriterion("picid >", value, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidGreaterThanOrEqualTo(Integer value) {
            addCriterion("picid >=", value, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidLessThan(Integer value) {
            addCriterion("picid <", value, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidLessThanOrEqualTo(Integer value) {
            addCriterion("picid <=", value, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidIn(List<Integer> values) {
            addCriterion("picid in", values, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidNotIn(List<Integer> values) {
            addCriterion("picid not in", values, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidBetween(Integer value1, Integer value2) {
            addCriterion("picid between", value1, value2, "picid");
            return (Criteria) this;
        }

        public Criteria andPicidNotBetween(Integer value1, Integer value2) {
            addCriterion("picid not between", value1, value2, "picid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andXminIsNull() {
            addCriterion("xmin is null");
            return (Criteria) this;
        }

        public Criteria andXminIsNotNull() {
            addCriterion("xmin is not null");
            return (Criteria) this;
        }

        public Criteria andXminEqualTo(String value) {
            addCriterion("xmin =", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminNotEqualTo(String value) {
            addCriterion("xmin <>", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminGreaterThan(String value) {
            addCriterion("xmin >", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminGreaterThanOrEqualTo(String value) {
            addCriterion("xmin >=", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminLessThan(String value) {
            addCriterion("xmin <", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminLessThanOrEqualTo(String value) {
            addCriterion("xmin <=", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminLike(String value) {
            addCriterion("xmin like", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminNotLike(String value) {
            addCriterion("xmin not like", value, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminIn(List<String> values) {
            addCriterion("xmin in", values, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminNotIn(List<String> values) {
            addCriterion("xmin not in", values, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminBetween(String value1, String value2) {
            addCriterion("xmin between", value1, value2, "xmin");
            return (Criteria) this;
        }

        public Criteria andXminNotBetween(String value1, String value2) {
            addCriterion("xmin not between", value1, value2, "xmin");
            return (Criteria) this;
        }

        public Criteria andYminIsNull() {
            addCriterion("ymin is null");
            return (Criteria) this;
        }

        public Criteria andYminIsNotNull() {
            addCriterion("ymin is not null");
            return (Criteria) this;
        }

        public Criteria andYminEqualTo(String value) {
            addCriterion("ymin =", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminNotEqualTo(String value) {
            addCriterion("ymin <>", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminGreaterThan(String value) {
            addCriterion("ymin >", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminGreaterThanOrEqualTo(String value) {
            addCriterion("ymin >=", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminLessThan(String value) {
            addCriterion("ymin <", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminLessThanOrEqualTo(String value) {
            addCriterion("ymin <=", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminLike(String value) {
            addCriterion("ymin like", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminNotLike(String value) {
            addCriterion("ymin not like", value, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminIn(List<String> values) {
            addCriterion("ymin in", values, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminNotIn(List<String> values) {
            addCriterion("ymin not in", values, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminBetween(String value1, String value2) {
            addCriterion("ymin between", value1, value2, "ymin");
            return (Criteria) this;
        }

        public Criteria andYminNotBetween(String value1, String value2) {
            addCriterion("ymin not between", value1, value2, "ymin");
            return (Criteria) this;
        }

        public Criteria andXmaxIsNull() {
            addCriterion("xmax is null");
            return (Criteria) this;
        }

        public Criteria andXmaxIsNotNull() {
            addCriterion("xmax is not null");
            return (Criteria) this;
        }

        public Criteria andXmaxEqualTo(String value) {
            addCriterion("xmax =", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxNotEqualTo(String value) {
            addCriterion("xmax <>", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxGreaterThan(String value) {
            addCriterion("xmax >", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxGreaterThanOrEqualTo(String value) {
            addCriterion("xmax >=", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxLessThan(String value) {
            addCriterion("xmax <", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxLessThanOrEqualTo(String value) {
            addCriterion("xmax <=", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxLike(String value) {
            addCriterion("xmax like", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxNotLike(String value) {
            addCriterion("xmax not like", value, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxIn(List<String> values) {
            addCriterion("xmax in", values, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxNotIn(List<String> values) {
            addCriterion("xmax not in", values, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxBetween(String value1, String value2) {
            addCriterion("xmax between", value1, value2, "xmax");
            return (Criteria) this;
        }

        public Criteria andXmaxNotBetween(String value1, String value2) {
            addCriterion("xmax not between", value1, value2, "xmax");
            return (Criteria) this;
        }

        public Criteria andYmaxIsNull() {
            addCriterion("ymax is null");
            return (Criteria) this;
        }

        public Criteria andYmaxIsNotNull() {
            addCriterion("ymax is not null");
            return (Criteria) this;
        }

        public Criteria andYmaxEqualTo(String value) {
            addCriterion("ymax =", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxNotEqualTo(String value) {
            addCriterion("ymax <>", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxGreaterThan(String value) {
            addCriterion("ymax >", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxGreaterThanOrEqualTo(String value) {
            addCriterion("ymax >=", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxLessThan(String value) {
            addCriterion("ymax <", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxLessThanOrEqualTo(String value) {
            addCriterion("ymax <=", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxLike(String value) {
            addCriterion("ymax like", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxNotLike(String value) {
            addCriterion("ymax not like", value, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxIn(List<String> values) {
            addCriterion("ymax in", values, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxNotIn(List<String> values) {
            addCriterion("ymax not in", values, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxBetween(String value1, String value2) {
            addCriterion("ymax between", value1, value2, "ymax");
            return (Criteria) this;
        }

        public Criteria andYmaxNotBetween(String value1, String value2) {
            addCriterion("ymax not between", value1, value2, "ymax");
            return (Criteria) this;
        }

        public Criteria andPathIsNull() {
            addCriterion("path is null");
            return (Criteria) this;
        }

        public Criteria andPathIsNotNull() {
            addCriterion("path is not null");
            return (Criteria) this;
        }

        public Criteria andPathEqualTo(String value) {
            addCriterion("path =", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotEqualTo(String value) {
            addCriterion("path <>", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThan(String value) {
            addCriterion("path >", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThanOrEqualTo(String value) {
            addCriterion("path >=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThan(String value) {
            addCriterion("path <", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThanOrEqualTo(String value) {
            addCriterion("path <=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLike(String value) {
            addCriterion("path like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotLike(String value) {
            addCriterion("path not like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathIn(List<String> values) {
            addCriterion("path in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotIn(List<String> values) {
            addCriterion("path not in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathBetween(String value1, String value2) {
            addCriterion("path between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotBetween(String value1, String value2) {
            addCriterion("path not between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andConfIsNull() {
            addCriterion("conf is null");
            return (Criteria) this;
        }

        public Criteria andConfIsNotNull() {
            addCriterion("conf is not null");
            return (Criteria) this;
        }

        public Criteria andConfEqualTo(Boolean value) {
            addCriterion("conf =", value, "conf");
            return (Criteria) this;
        }

        public Criteria andConfNotEqualTo(Boolean value) {
            addCriterion("conf <>", value, "conf");
            return (Criteria) this;
        }

        public Criteria andConfGreaterThan(Boolean value) {
            addCriterion("conf >", value, "conf");
            return (Criteria) this;
        }

        public Criteria andConfGreaterThanOrEqualTo(Boolean value) {
            addCriterion("conf >=", value, "conf");
            return (Criteria) this;
        }

        public Criteria andConfLessThan(Boolean value) {
            addCriterion("conf <", value, "conf");
            return (Criteria) this;
        }

        public Criteria andConfLessThanOrEqualTo(Boolean value) {
            addCriterion("conf <=", value, "conf");
            return (Criteria) this;
        }

        public Criteria andConfIn(List<Boolean> values) {
            addCriterion("conf in", values, "conf");
            return (Criteria) this;
        }

        public Criteria andConfNotIn(List<Boolean> values) {
            addCriterion("conf not in", values, "conf");
            return (Criteria) this;
        }

        public Criteria andConfBetween(Boolean value1, Boolean value2) {
            addCriterion("conf between", value1, value2, "conf");
            return (Criteria) this;
        }

        public Criteria andConfNotBetween(Boolean value1, Boolean value2) {
            addCriterion("conf not between", value1, value2, "conf");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userpic
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userpic
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}